// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwXrVI-jHCpGdMFl2C5KeuVx2OelXX6Ao',
    appId: '1:469188073066:web:63ebf9f4e33f4476641c13',
    messagingSenderId: '469188073066',
    projectId: 'workoutapp-76e27',
    authDomain: 'workoutapp-76e27.firebaseapp.com',
    storageBucket: 'workoutapp-76e27.firebasestorage.app',
    measurementId: 'G-JR863BH3PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEw_Jk33u0nPvb7MzFBuA2p86s9j6AIc',
    appId: '1:469188073066:android:e10e2ba8ad0775d5641c13',
    messagingSenderId: '469188073066',
    projectId: 'workoutapp-76e27',
    storageBucket: 'workoutapp-76e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEH7HSLJa2XJSPSVcGEW2BbTBX9ISA8tk',
    appId: '1:469188073066:ios:5955d15487e25ae0641c13',
    messagingSenderId: '469188073066',
    projectId: 'workoutapp-76e27',
    storageBucket: 'workoutapp-76e27.firebasestorage.app',
    iosBundleId: 'com.example.workoutapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEH7HSLJa2XJSPSVcGEW2BbTBX9ISA8tk',
    appId: '1:469188073066:ios:5955d15487e25ae0641c13',
    messagingSenderId: '469188073066',
    projectId: 'workoutapp-76e27',
    storageBucket: 'workoutapp-76e27.firebasestorage.app',
    iosBundleId: 'com.example.workoutapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwXrVI-jHCpGdMFl2C5KeuVx2OelXX6Ao',
    appId: '1:469188073066:web:dca2836744b03243641c13',
    messagingSenderId: '469188073066',
    projectId: 'workoutapp-76e27',
    authDomain: 'workoutapp-76e27.firebaseapp.com',
    storageBucket: 'workoutapp-76e27.firebasestorage.app',
    measurementId: 'G-W4HC2G33J9',
  );

}